(function(g){var window=this;var N2=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.Ez(a),kind:a.o,name:a.u,id:a.H,is_servable:a.C,is_default:a.isDefault,is_translateable:a.D,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},O2=function(a){return a.g?a.g.languageCode:a.i},Spa=function(a,b){var c=new g.Dz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.C=a.C;c.D=a.D;c.A=a.A;c.F=a.F;c.g=b;return c},Tpa=function(){this.i=[];
this.g=[]},P2=function(a,b){return b?a.g.concat(a.i):a.g},Q2=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Za(c,(0,g.x)(b.Zq,b))||c.push(b);break;default:c=a.g,g.Za(c,(0,g.x)(b.Zq,b))||c.push(b)}},R2=function(a){g.D.call(this);
this.Wa=a;this.i=new Tpa;this.u=[]},S2=function(a,b,c){R2.call(this,a);
this.g=null;this.u=b.yu;this.l=c},T2=function(){this.Ua=[]},U2=function(a,b,c,d,e,f){g.D.call(this);
this.H=a;this.l=b;this.R=g.W(b);this.u=new T2;this.g=null;this.C=d;this.I=f;this.i=this.o=null;this.M=c;this.A=e||!1;this.D=new g.I(this.Zw,1E3,this);g.F(this,this.D);this.F=new g.ls(this);g.F(this,this.F);this.F.K(b,"SEEK_COMPLETE",this.Gx);this.Gx();this.Zw()},V2=function(a,b){b-=a.l.yb();
var c=a.g;a.g=g.Xa(a.M.xf(b).g);c!=a.g&&a.I&&a.I()},W2=function(a,b){var c=g.Dv(g.Qv(b,a.H,{})),d={format:"RAW",
withCredentials:!0};a.A&&(d.responseType="arraybuffer");a.i=g.yq(c,d,3,100).then((0,g.x)(a.GK,a));a.o=b;c=a.u;d=a.o.g[0].i;var e=g.qb(c.Ua,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ua[e-1]&&e<c.Ua.length&&1==c.Ua[e]-d?(g.eb(c.Ua,e),g.eb(c.Ua,e-1)):0<e&&1==d-c.Ua[e-1]?c.Ua[e-1]=d:e<c.Ua.length&&1==c.Ua[e]-d?c.Ua[e]=d:(g.nb(c.Ua,e,0,d),g.nb(c.Ua,e+1,0,d)))},X2=function(a,b){R2.call(this,g.W(b));
this.g=a;this.C=b;this.l=null;this.o=!1;this.A=g.fz(g.W(this.C))&&!this.g.i},Y2=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.JO(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Dz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Upa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},Z2=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.JO(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},$2=function(a,b,c,d,e){R2.call(this,e||null);
c=c||g.Fp(a).hl||"";c=c.split("_").join("-");this.o=g.Hp(a,{hl:c});this.l=b;this.A=!!d;this.C={};this.g=null},a3=function(a){if(!Vpa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Wpa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},b3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.RD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.g=k},c3=function(a,b,c,d,e){g.RD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.g=[]},e3=function(a){a=void 0===a?{}:a;
var b="_"+d3++;return new c3(0,0x8000000000000,0,b,a)},g3=function(a,b,c,d,e,f){var k={};
g.Sa(k,b);g.Sa(k,a.params);g.Sa(k,c);var l={};g.Sa(l,b.ub);a.params.ub&&g.Sa(l,a.params.ub);g.Sa(l,c.ub);k.ub=l;g.V.call(this,{B:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==k.Ae?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{B:"span",G:"captions-text",L:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.P=!1;this.o=a;this.X=this.S=null;this.Pa=e;this.Na=f;this.D=null;this.Y=.96*e;this.wa=.96*f;this.l=k;this.Ia=c;this.A=this.i["captions-text"];this.Ca=
null!=this.A.style["box-decoration-break"]||null!=this.A.style["-webkit-box-decoration-break"];this.W=d/360*16;this.type=0;this.la=this.W*f3(l);a=new g.ps(this.element,!0);g.F(this,a);a.subscribe("dragstart",this.XF,this);a.subscribe("dragmove",this.WF,this);a.subscribe("dragend",this.VF,this);this.va=this.ma=0;b="";this.l.windowOpacity&&(a=a3(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":Xpa[this.l.textAlign]};
this.Ca&&(a["border-radius"]=b?this.la/8+"px":"");if(this.u=2==this.o.params.Ae||3==this.o.params.Ae)b=this.element,c="vertical-rl",1==this.l.CA&&(c="vertical-lr"),g.Ld&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.bg(b,"-o-writing-mode",c),g.bg(b,"-webkit-writing-mode",c),g.bg(b,"writing-mode",c),g.bg(b,"text-orientation","upright"),g.J(b,"ytp-vertical-caption"),3==this.o.params.Ae&&(g.bg(b,"text-orientation",""),g.bg(b,"transform","rotate(180deg)"));g.bg(this.element,a);switch(this.l.Tf){case 0:case 1:case 2:g.J(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},f3=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},h3=function(a,b){var c={},d=b.background?b.background:a.l.ub.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.ub.backgroundOpacity;d=a3(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ca&&(c["box-decoration-break"]="clone",c["border-radius"]=a.la/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.W*f3(b)+"px";d=1;e=b.color||a.l.ub.color;if(b.color||null!=b.textOpacity)e=a3(e),d=null==b.textOpacity?a.l.ub.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Gu&&(k=e=b.Gu);var l=a.W/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.gq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.ub.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Pe&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.UD&&(c.visibility="hidden");1==b.WD&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.kz||g.oz,3==a.o.params.Ae?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.ze||2==b.ze||3==b.ze||4==b.ze||5==b.ze)if(g.kz)c["font-weight"]="bold";else switch(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",b.ze){case 4:case 3:c["text-emphasis-position"]="under left";c["webkit-text-emphasis-position"]="under left";break;
case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},i3=function(a){a.D=g.Rd("SPAN");
g.bg(a.D,{display:"block"});g.J(a.D,"caption-visual-line");a.A.appendChild(a.D)},j3=function(a,b){var c=g.Rd("SPAN");
g.bg(c,{display:"inline-block","white-space":"pre-wrap"});g.bg(c,h3(a,b));c.classList.add("ytp-caption-segment");a.D.appendChild(c);c.previousElementSibling&&(g.bg(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.bg(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},k3=function(a,b,c){a.P=a.P||!!c;
var d={};g.Sa(d,a.l.ub);g.Sa(d,c||b.g);g.Sa(d,a.Ia.ub);(c=!a.D)&&i3(a);for(var e=a.S&&a.X&&g.cc(d,a.X)?a.S:j3(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!c?(i3(a),e=j3(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Sd(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.kz||!g.fg(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.fg(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),g.Nd?
g.bg(e,m,"1em"):g.bg(e,m,"0.5em")))}a.X=d;a.S=e;a.C.push(b)},l3=function(){},n3=function(){this.o=this.i=this.mode=this.l=0;
this.u=new m3(this);this.A=new m3(this);this.g=[];this.clear()},Ypa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Al:a,
Bl:b,result:0};a=o3[a];b=o3[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{Al:a,Bl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Al:a,Bl:b,result:2};return{Al:a,Bl:b,result:3}},Zpa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,p3(a.u,b,c,d))},$pa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?Zpa(a,d.Au,d.Bu,b):1==d.type&&a.l&496&&p3(a.A,d.Au,d.Bu,b)}a.g.length=0},q3=function(){this.g=0},r3=function(){this.i=this.l=this.g=0},s3=function(){this.timestamp=this.Ud=0},t3=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new s3}this.g=this.i=this.row=0;this.style=new q3;this.u=a;this.o=0},u3=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.l[m][q];
if(0!=t.Ud){0==c&&(c=m,d=q);n=String.fromCharCode(t.Ud);var w=t.timestamp;w<e&&(e=w);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Ud||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.l[k][m],t=q.Ud,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),w=q.timestamp,w<=e&&(e=w),l+=n,q.reset()),32==m||0==t)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},eqa=function(a,b){switch(a){case 0:return aqa[(b&127)-32];
case 1:return bqa[b&15];case 2:return cqa[b&31];case 3:return dqa[b&31]}return 0},v3=function(a){return a.l[a.row][a.i]},w3=function(a,b,c){2<=b&&1<a.i&&(--a.i,v3(a).Ud=0);
var d=v3(a);d.timestamp=a.u.i+0;d.Ud=eqa(b,c);32>a.i&&a.i++},x3=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].dg(a.l[c+e][f])},y3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},z3=function(a){a.row=0<a.g?a.g:1;
a.i=1;y3(a,0,15)},A3=function(a){this.o=a;
this.u=0;this.style=new q3;this.A=new t3(a);this.C=new t3(a);this.D=new t3(a);this.i=this.A;this.l=this.C;this.g=this.i},B3=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:u3(d,c),z3(a.i),z3(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(u3(d,c),y3(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},C3=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},D3=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},m3=function(a){this.i=a;
this.g=new r3;this.u=0;this.l=new A3(a);this.A=new A3(a);this.o=this.l},p3=function(a,b,c,d){a.g.update();
b=Ypa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Al;c=b.Bl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&w3(a,0,b),c&96&&w3(a,0,c),0!=b&&0!=c&&3==a.style.g&&u3(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;x3(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));y3(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:w3(b.g,0,32);break a;case 48:57==c?(d=b.g,v3(d).Ud=0,32>d.i&&d.i++):w3(b.g,1,c&15)}break;case 2:c&32&&w3(b.g,2,c&31);break;case 3:c&32&&w3(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:C3(b);break;case 33:d=
b.g;1<d.i&&(--d.i,v3(d).Ud=0);break;case 36:d=b.g;b=v3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:B3(b,2,d);break;case 38:B3(b,3,d);break;case 39:B3(b,4,d);break;case 40:w3(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);z3(d);D3(b);break;case 43:D3(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:u3(a,d)}y3(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;u3(a,d);x3(a,b,b+1,a.g-1);y3(a,a.row,1)}break;case 46:y3(b.l,0,15);break;case 47:u3(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,C3(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},E3=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.cd){var n=f[1],q=f[2],t=f[3];l.getAttribute("p");var w=g.gq();l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");t.getAttribute("t");f=w?g.Rd("DIV"):g.Rd("RUBY");l=l.textContent;var z=g.Rd("SPAN");z.textContent=l;f.appendChild(z);n.getAttribute("p");z=w?g.Rd("DIV"):g.Rd("RP");l=n.textContent;z.textContent=l;f.appendChild(z);k=k[q.getAttribute("p")];l=q.textContent;q=w?g.Rd("DIV"):g.Rd("RT");q.textContent=l;f.appendChild(q);l=k.cd;if(10==l||11==l||12==l||13==l||14==l)if(g.bg(q,"text-emphasis",
"filled circle"),g.bg(q,"webkit-text-emphasis","filled circle"),k.cd==k.cd==11||13==k.cd)g.bg(q,"webkit-text-emphasis-position","under left"),g.bg(q,"text-emphasis-position","under left");q=!0;if(4==k.cd||7==k.cd||12==k.cd||14==k.cd)g.bg(f,"ruby-position","over"),g.bg(f,"-webkit-ruby-position","before");else if(5==k.cd||6==k.cd||11==k.cd||13==k.cd)g.bg(f,"ruby-position","under"),g.bg(f,"-webkit-ruby-position","after"),q=!1;t.getAttribute("p");l=t.textContent;t=w?g.Rd("DIV"):g.Rd("RP");t.textContent=
l;f.appendChild(t);w&&(w=q,g.bg(f,{display:"inline-block",position:"relative"}),t=f.firstElementChild.nextElementSibling,g.bg(t,"display","none"),t=t.nextElementSibling,g.bg(t,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.bg(f.lastElementChild,"display","none"),w?(g.bg(f,"padding-top","0.6em"),g.bg(t,"top","0")):(g.bg(f,"padding-bottom","0.6em"),g.bg(t,"bottom","0")));return new b3(a,b,e,c,f,d,m)}switch(m.cd){case 9:case 10:m.ze=
1;break;case 11:m.ze=2;break;case 12:m.ze=3;break;case 13:m.ze=4;break;case 14:m.ze=5}return new b3(a,b,e,c,l.textContent||"",d,m)},F3=function(){g.D.apply(this,arguments)},G3=function(a){F3.call(this);
this.l={};this.F={};this.H={};this.u="_"+d3++;this.A=a;this.D={};this.i=this.g=null;this.C=!0},H3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},I3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},J3=function(a,b){var c=H3(a,b);
return void 0!=c?c:null},L3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return K3.test(c),c},M3=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.H[d]:a.A);d=J3(b,"mh");null!=d&&(c.Tq=d);d=J3(b,"ju");null!=d&&(c.textAlign=d);d=J3(b,"pd");null!=d&&(c.Ae=d);d=J3(b,"sd");null!=d&&(c.CA=d);d=L3(b,"wfc");null!=d&&(c.windowColor=d);d=H3(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},N3=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.F[d]);d=J3(b,"ap");null!=d&&(c.Tf=d);d=H3(b,"cc");null!=d&&(c.Ol=d);d=H3(b,"ah");null!=d&&(c.Qe=d);d=H3(b,"rc");null!=d&&(c.Bk=d);d=H3(b,"av");null!=d&&(c.Gg=d);return c},O3=function(a,b,c,d){var e={};
g.Sa(e,N3(a,b));g.Sa(e,M3(a,b));d?g.cc(e,a.A)?(d=a.u,e=a.A):d="_"+d3++:d=b.getAttribute("id")||"_"+d3++;a=H3(b,"t")+c;b=H3(b,"d")||0x8000000000000;if(2==e.Ae||3==e.Ae)c=e.Bk,e.Bk=e.Ol,e.Ol=c;return new c3(a,b,0,d,e)},P3=function(a,b,c,d,e,f,k){g3.call(this,a,b,c,d,e,f,k);
this.type=1},Q3=function(a,b,c){this.C=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},R3=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},S3=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},T3=function(a,b){F3.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new n3;this.g.l=1<<this.track},V3=function(a){if("string"===typeof a)return!1;
a=new Q3(a,8,0);return U3(a)},U3=function(a){if(!(a.g<a.i.byteLength)||1380139777!=S3(a))return!1;
a.version=R3(a);if(1<a.version)return!1;R3(a);R3(a);R3(a);return!0},W3=function(a,b,c,d,e,f,k){g3.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.F=[];this.I=this.H=this.ea=0;this.M=NaN;this.ya=0;this.Ea=null;this.da=new g.I(this.LK,433,this);g.F(this,this.da);g.bg(this.element,"overflow","hidden")},fqa=function(a,b){return(a.u?b.offsetHeight:b.offsetWidth)+1},gqa=function(a){if(isNaN(a.M)){var b=a.l.Ol;
if(b){var c=g.Rd("SPAN");g.ae(c,"\u2013".repeat(b));g.bg(c,h3(a,a.l.ub));a.A.appendChild(c);a.M=c.offsetWidth;a.A.removeChild(c)}else a.M=0}return a.M},hqa=function(a,b){if(!b)return"";
a.u&&1!=a.o.params.CA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},X3=function(a){a.F=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.Bk,c=0,d=0,e=a.F.length-1;c<b&&-1<e;){var f=a.F[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.F.length<b&&(d*=b/a.F.length);a.H=d;a.I=Math.max(gqa(a),a.ya,fqa(a,a.A))},iqa=function(a,b){X3(a);
var c=a.F.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.ea){var d=0<c&&0==a.ea;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.yn(a.da));g.bg(a.A,"transform",hqa(a,c));a.ea=c}X3(a)},Y3=function(){F3.call(this)},Z3=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Pe=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType){q=new b3(b,c,d,e.id,q.nodeValue,f||0<n,g.Zb(l)?void 0:l);m.push(q);var t=e;g.F(t,q);t.g.push(q)}else t={},g.Sa(t,l),Z3(a,b,c,d,e,!0,q,t,m)}},$3=function(a){var b=0;
a=g.p(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},a4=function(a,b,c,d){d=Object.assign({Tq:0},d);
return new c3(a,b,c,"_"+d3++,d)},b4=function(a){g.D.call(this);
this.i=a;this.g=null},e4=function(a){g.IO.call(this,a);
this.l=g.W(a);this.O=a.getVideoData();this.ma=g.vK(a);this.M=a;var b=null,c=g.no("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Xn(c));this.Z=b;this.o={ub:{}};this.u={ub:{}};this.F=[];this.R={};this.S={};this.I=!1;this.da=g.KO(this.O,this.M);this.va=!!this.O.captionTracks.length;this.wa=!!this.O.ej;this.na="3"==this.l.l;b=a.app.u;c=!(!b||!b.Pk());this.la=!(!b||!b.Bh());this.A=this.na&&c&&!this.da;this.H=!this.A&&this.na&&this.la&&this.da;this.i=this.C=this.D=this.P=this.ea=null;this.X=
new b4(this.l);g.F(this,this.X);c=b=this.g=null;this.A||(b=new g.vn(this.RA,void 0,this),g.F(this,b),c=new g.I(this.nM,2E3,this),g.F(this,c));this.W=b;this.Y=c;this.ba=new g.ls(this);g.F(this,this.ba);this.A||this.ba.K(a,"resize",this.Vs);this.ba.K(a,"onPlaybackAudioChange",this.nI);this.ba.K(a,g.UD("captions"),this.cF,this);this.ba.K(a,"crx_captions",this.dF,this);c4(this,d4(this,"display-settings")||{})},f4=function(a){if(1==a.l.Yf||1==a.O.Yf||"alwayson"==g.CB(a.O,"yt:cc"))return!0;
if(2==a.l.Yf){var b=d4(a,"module-enabled");if(null!=b)return!!b}if(a.O.captionTracks.length)var c=a.player.getAudioTrack().ip;return"ON"==c||"on"==g.CB(a.O,"yt:cc")},g4=function(a,b){if(a.g&&(void 0===b||!b)||!a.O.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Zl||"FORCED_ON"==c.ip},i4=function(a,b){if(a.i){if(a.C&&a.C.g)return a.C.g;
var c=b;c||(c=a.wa?!1:a.va?!1:!0);c=P2(a.i.i,c);for(var d=[a.O.Xf,a.l.Xf,g.CB(a.O,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(O2(c[f])==d[e])return c[f];return a.C&&a.C.Bp?a.C.Bp:(d=c.find(function(k){return k.isDefault}))?d:c[0]||h4(a)}return null},h4=function(a){return a.C&&a.C.Zl},j4=function(a){var b=h4(a);
return!!b&&a.g==b},k4=function(a,b){for(var c=a.M.app.u.ga().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},m4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.I=c,a.I&&l4(a,"module-enabled",!!b));a.g=b;g4(a)&&(a.g=h4(a));a.load()},jqa=function(a,b){var c=a.ma.getVideoContentRect(!0).height;
if(!c)return null;var d=a.ma.getPlayerSize();switch(null!=b.params.Tq?b.params.Tq:1<b.g.length?1:0){case 1:return new P3(b,a.o,a.u,c,d.width,d.height,a.l.experiments);case 2:return new W3(b,a.o,a.u,c,d.width,d.height,a.l.experiments);default:return new g3(b,a.o,a.u,c,d.width,d.height,a.l.experiments)}},c4=function(a,b,c){var d=n4.ub;
a.o={};g.Sa(a.o,n4);a.o.ub={};g.Sa(a.o.ub,d);a.u={ub:{}};var e=b.backgroundOverride?a.u:a.o,f=b.background||d.background;K3.test(f);e.ub.background=f;e=b.colorOverride?a.u:a.o;f=b.color||d.color;K3.test(f);e.ub.color=f;e=b.windowColorOverride?a.u:a.o;f=b.windowColor||n4.windowColor;K3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.u:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.ub.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.u:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.ub.fontSizeIncrement=f;f=b.fontStyleOverride?a.u:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.Pe?3:d.bold?1:d.Pe?2:0);f=f.ub;switch(e){case 1:f.bold=!0;delete f.Pe;break;case 2:delete f.bold;f.Pe=!0;break;case 3:f.bold=!0;f.Pe=!0;break;default:delete f.bold,delete f.Pe}e=b.textOpacityOverride?a.u:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.ub.textOpacity=f;e=b.windowOpacityOverride?a.u:a.o;f=b.windowOpacity;null==f&&(f=n4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.u:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.ub.charEdgeStyle=f;e=b.fontFamilyOverride?a.u:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.ub.fontFamily=f;a.loaded&&a.Vs();c&&l4(a,"display-settings",b)},p4=function(a,b){if(b&&!a.D){var c=e3({Ae:0,
lang:"en"});a.D=[c,new b3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.CK(a.player,a.D)}else!b&&a.D&&(o4(a,a.D),a.D=null)},o4=function(a,b){g.EK(a.player,b);
(0,g.y)(b,function(c){g.fb(this.F,c)},a);
a.W.Aj()},d4=function(a,b){if(!a.Z)return null;
try{var c=a.Z.get(b)}catch(d){a.Z.remove(b)}return c},l4=function(a,b,c){if(a.Z)try{a.Z.set(b,c)}catch(d){}};
g.lC.prototype.gj=g.ca(13,function(){for(var a=g.Cd(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Wd(a[b])});
g.qQ.prototype.gj=g.ca(12,function(){this.g.gj()});
g.lC.prototype.Pk=g.ca(11,function(){return!!this.g.textTracks});
g.qQ.prototype.Pk=g.ca(10,function(){return this.g.Pk()});
g.lC.prototype.Yi=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.qQ.prototype.Yi=g.ca(8,function(a){this.g.Yi(a)});
g.cC.prototype.Bh=g.ca(7,function(){});
g.lC.prototype.Bh=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.qQ.prototype.Bh=g.ca(5,function(){return this.g.Bh()});
g.Dz.prototype.Zq=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.Zt.prototype.rm=g.ca(2,function(a){return(a=this.kg(a))?a.i:0});
g.zw.prototype.rm=g.ca(1,function(){return 0});
var kqa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,K3=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(R2,g.D);R2.prototype.Cz=function(){return!1};
R2.prototype.V=function(){this.Hg();g.D.prototype.V.call(this)};
g.r(S2,R2);S2.prototype.Rq=function(a,b,c){b=this.zj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Hg();this.g=g.Yp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
S2.prototype.Sq=function(a){if(this.l)for(var b=g.p(this.l.captionTracks),c=b.next();!c.done;c=b.next())Q2(this.i,c.value);a()};
S2.prototype.zj=function(a,b){var c=a.F,d={fmt:b};("srv3"==b||"3"==b)&&this.Wa&&g.N(this.Wa.experiments,"caption_rendering_features")&&(g.gq()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3}));a.g&&(d.tlang=O2(a));return g.Hp(c,d)};
S2.prototype.Hg=function(){this.g&&this.g.abort()};
T2.prototype.contains=function(a){a=g.qb(this.Ua,a);return 0<=a||0>a&&1==(-a-1)%2};
T2.prototype.length=function(){return this.Ua.length/2};
g.r(U2,g.D);g.h=U2.prototype;g.h.V=function(){g.D.prototype.V.call(this);this.i&&this.i.cancel()};
g.h.Gx=function(){V2(this,this.l.getCurrentTime())};
g.h.reset=function(){this.u=new T2;this.i&&(this.i.cancel(),this.i=null)};
g.h.Zw=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Hf(a);!a||this.i||this.g&&30<this.g.startTime-this.l.getCurrentTime()||(a=this.g,a=a.g.mi(a),a.g[0].duration?(this.u.contains(a.g[0].i)||W2(this,a),this.g=g.Xa(a.g)):!g.N(this.R.experiments,"force_caption_seek_for_live_killswitch")&&this.g&&this.g.u&&this.g.u+this.l.yb()<this.l.getCurrentTime()&&V2(this,this.l.getCurrentTime()));this.D.start()};
g.h.GK=function(a){var b=!(this.A?a.response:a.responseText)||400<=a.status,c=g.Gw(a);c?(a=g.Qv(this.o,this.H,{}),b=this.o,g.Lv(b.i,a,c),b.requestId=a.get("req_id"),W2(this,this.o)):(b||null===this.C||(c=this.o.g[0],this.A?this.C(a.response,1E3*(c.startTime+this.l.yb())):this.C(a.responseText,1E3*(c.startTime+this.l.yb()))),this.i=this.o=null)};
g.r(X2,R2);g.h=X2.prototype;g.h.Rq=function(a,b,c){this.Hg();b=Upa(this,a.getId());b||(b=a.i,b=this.g.i?Z2(this,b,"386"):Z2(this,b));if(b){var d=1E3*(b.index.rm(b.index.te())-b.index.Kc(b.index.te()));this.l=new U2(new g.Gv,this.C,b,function(e,f){c(e,a,f,d)},this.A||g.xv(b.info),(0,g.x)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.Cz=function(){var a=this.o;this.o=!1;return a};
g.h.Sq=function(a){var b;this.A?b=[new g.Dz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Dz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?Y2(this,"386"):Y2(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())Q2(this.i,c.value);a()};
g.h.Hg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.zj=function(){return""};
g.r($2,R2);$2.prototype.Rq=function(a,b,c){b=this.zj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Hg();this.g=g.Yp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
$2.prototype.Sq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.Hp(b,c);c=(0,g.x)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.p(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),w="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
Q2(this.i,new g.Dz({languageCode:f,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:w,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),q=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:t},this.C[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.Hg();this.g=g.Yp(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
$2.prototype.zj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=O2(a));return c=g.Hp(c,d)};
$2.prototype.Hg=function(){this.g&&this.g.abort()};
var Wpa=/#(.)(.)(.)/,Vpa=/^#(?:[0-9a-f]{3}){1,2}$/i;var Xpa=["left","right","center","justify"];var n4={windowColor:"#080808",windowOpacity:0,textAlign:2,Tf:7,Qe:50,Gg:100,ub:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(b3,g.RD);b3.prototype.toString=function(){return g.RD.prototype.toString.call(this)};g.r(c3,g.RD);c3.prototype.toString=function(){return g.RD.prototype.toString.call(this)};
var d3=0;g.r(g3,g.V);g.h=g3.prototype;g.h.XF=function(a,b){var c=g.sg(this.element,this.element.parentElement);this.ma=a-c.x;this.va=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.WF=function(a,b){var c=g.vg(this.element),d=a-this.ma-.02*this.Pa,e=b-this.va-.02*this.Na,f=(d+c.width/2)/this.Y*3;f=Math.floor(g.nd(f,0,2));var k=(e+c.height/2)/this.wa*3;k=Math.floor(g.nd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.Y;d=100*g.nd(d,0,1);c=(e+k/2*c.height)/this.wa;c=100*g.nd(c,0,1);this.o.params.Tf=l;this.o.params.Gg=c;this.o.params.Qe=d;this.l.Tf=l;this.l.Gg=c;this.l.Qe=d;this.bA()};
g.h.VF=function(){g.Hn(this.element,"ytp-dragging")};
g.h.bA=function(){this.xh(this.C)};
g.h.xh=function(a){var b=Math.min(this.Pv(),this.Y),c=this.Ov(),d="";3==this.o.params.Ae&&(d="rotate(180deg)");g.bg(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Vo(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Qe+2;d=this.l.Tf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.A.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.Gg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.bg(this.element,a)};
g.h.Vo=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.P||this.C.length>b)b=0,this.P=!1,this.C=[],this.D=this.X=this.S=null,g.Ud(this.A);for(;b<a.length;b++)k3(this,a[b])};
g.h.Pv=function(){return 0};
g.h.Ov=function(){return 0};
g.h.toString=function(){return g.V.prototype.toString.call(this)};l3.prototype.u=function(){};n3.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
n3.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var o3=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];q3.prototype.set=function(a){this.g=a};
q3.prototype.get=function(){return this.g};
r3.prototype.clear=function(){this.g=0};
r3.prototype.update=function(){this.g=2==this.g?1:0};
r3.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
s3.prototype.dg=function(a){this.Ud=a.Ud;this.timestamp=a.timestamp};
s3.prototype.reset=function(){this.timestamp=this.Ud=0};
t3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
t3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Ud?a+"_":a+String.fromCharCode(d.Ud)}a+="\n"}return a};
t3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var aqa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],bqa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],cqa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],dqa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];A3.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.C;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.C.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
m3.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.r(F3,g.D);F3.prototype.reset=function(){};g.r(G3,F3);G3.prototype.reset=function(){this.D={};this.i=this.g=null;this.C=!0};
G3.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Sa(l,this.l[m]);m=I3(c,"b");null!=m&&(l.bold=
m);m=I3(c,"i");null!=m&&(l.Pe=m);m=I3(c,"u");null!=m&&(l.underline=m);m=J3(c,"et");null!=m&&(l.charEdgeStyle=m);m=J3(c,"of");null!=m&&(l.offset=m);m=L3(c,"bc");null!=m&&(l.background=m);m=L3(c,"ec");null!=m&&(l.Gu=m);m=L3(c,"fc");null!=m&&(l.color=m);m=J3(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=H3(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=H3(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=H3(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=J3(c,"rb");null!=m&&10!=m&&0!=m&&(l.cd=10<m?m-1:m);
m=J3(c,"hg");null!=m&&(l.WD=m);c=J3(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.ze=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.H[d]=M3(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=N3(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=O3(this,d,e,!1);g.F(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.u;m=!!I3(d,"a");n=(H3(d,"t")||0)+n;var q=H3(d,"d")||5E3;m||(!this.C&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var t=m?6:5,w=this.l[d.getAttribute("p")],z=[].concat(g.ea(d.childNodes));z.length&&(this.C=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var E=z[C],G=void 0;0<C&&(m=!0);var H=void 0;1==E.nodeType&&(H=E);if(H&&"s"==H.tagName){if((E=this.l[H.getAttribute("p")])&&E.cd&&(1==E.cd?(E=z.slice(C,
C+4),4==E.length&&(G=E3(n,q,l,m,t,E,this.l),C+=3)):G=E3(n,q,l,m,t,[H],this.l)),!G){var P=H;G=n;H=q;E=l;var Q=m,ia=t,oa=P.textContent?P.textContent:"",Va=this.l[P.getAttribute("p")];P=H3(P,"t")||0;G=new b3(G+P,H-P,ia,E,oa,Q,Va)}}else G=new b3(n,q,t,l,E.textContent||"",m,w);k.push(G);this.i=G}if(0<k.length)for(k[0].windowId==this.u&&(this.g=O3(this,d,e,!0),g.F(this,this.g),c.push(this.g)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.F(l,k),l.g.push(k),c.push(k)}e=
c}else e=[];return e};g.r(P3,g3);P3.prototype.Vo=function(a){var b=this.o.g;g3.prototype.Vo.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.g==e)var d=f;else{d={};g.Sa(d,c.g);g.Sa(d,lqa);var e=c.g;var f=d}k3(this,c,d)}};
var lqa={UD:!0};g.r(Q3,l3);Q3.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+d3++;c=c/1E3-this.C;d=d/1E3-this.C;a=new c3(c,d-c,5,f,{textAlign:0,Tf:0,Qe:2.5*b,Gg:5.33*a});e=new b3(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.r(T3,F3);T3.prototype.o=function(a){a=new Q3(a,a.byteLength,this.i);if(U3(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=S3(a)*(1E3/45):1==a.version&&(a.o=4294967296*S3(a)+S3(a)),a.A=R3(a);0<a.A;a.A--){var b=R3(a),c=R3(a),d=R3(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,Au:c,Bu:d,order:b.g.length}))}$pa(this.g,a);return a.l}return[]};
T3.prototype.reset=function(){this.g.clear()};g.r(W3,g3);g.h=W3.prototype;g.h.bA=function(){g.zn(this.da)};
g.h.LK=function(){g.Hn(this.element,"ytp-rollup-mode");this.xh(this.Ea,!0)};
g.h.Ov=function(){return this.u?this.I:this.H};
g.h.Pv=function(){return this.u?this.H:this.I};
g.h.xh=function(a,b){this.Ea=a;if(this.o.params.Bk){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.ya=this.I;this.H=this.I=0;g3.prototype.xh.call(this,a);iqa(this,b);g3.prototype.xh.call(this,a)}else g3.prototype.xh.call(this,a)};g.r(Y3,F3);
Y3.prototype.o=function(a,b){for(var c=[],d=a.split(mqa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!nqa.test(f)){var l=q4.exec(f);if(l&&4<=l.length){var m=$3(l[1]),n=$3(l[2])-m;m+=k;var q,t=q=void 0,w=void 0,z=void 0,C=l[3];l={textAlign:2};C=g.p(C?C.split(" "):[]);for(var E=C.next();!E.done;E=C.next())if(E=E.value.split(":"),2==E.length){var G=E[1];switch(E[0]){case "line":E=G.split(",");E[0].endsWith("%")&&(z=E[0],l.Gg=Number.parseInt(z,10),2==E.length&&(w=E[1].trim()));break;case "position":E=G.split(",");
t=E[0];l.Qe=Number.parseInt(t,10);2==E.length&&(q=E[1].trim());break;case "align":switch(G){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Gg=100,w||(w="end"));if(!t)switch(l.textAlign){case 0:l.Qe=0;break;case 1:l.Qe=100;break;default:l.Qe=50}t=0;switch(w){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(q){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Tf=0>t||8<t?7:t;q=l;f=f.substring(q4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=a4(m,n,5,t),n=new b3(m,n,5,k.id,q,!1,g.Zb(f)?void 0:f),c.push(k),c.push(n),g.F(k,n),k.g.push(n);else for(w=q.split(oqa),1==w.length?(q=5,t=a4(m,n,q,t)):(z=q=6,t=Object.assign({Ol:32},t),t=new c3(m,n,z,"_"+d3++,t)),c.push(t),z=m,l=0;l<w.length;l++)C=w[l],0==l%2?(E=g.MY("<html>"+C+"</html>"),E.getElementsByTagName("parsererror").length?
(G=E.createElement("span"),G.appendChild(E.createTextNode(C))):G=E.firstChild,Z3(this,z,n-(z-m),q,t,0<l,G,f,c)):z=$3(C)+k}q4.lastIndex=0}}return c};
var nqa=/^NOTE/,mqa=/(?:\r\n|\r|\n){2,}/,q4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),oqa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(b4,g.D);b4.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
b4.prototype.reset=function(){this.g&&this.g.reset()};
b4.prototype.V=function(){this.clear();g.D.prototype.V.call(this)};g.r(e4,g.IO);g.h=e4.prototype;g.h.V=function(){if(this.A||this.H){var a=this.M.app.u;a&&a.gj()}else p4(this,!1);g.IO.prototype.V.call(this)};
g.h.Gk=function(){return this.na?this.A||this.H:g4(this)?!0:f4(this)};
g.h.load=function(){g.IO.prototype.load.call(this);var a=!g.N(this.l.experiments,"web_player_captions_track_list_changed_killswitch");this.C=this.player.getAudioTrack();if(this.i)this.g&&(this.X.clear(),this.A?k4(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.Rq(this.g,"srv3",(0,g.x)(this.uL,this)),!a||this.A||this.H||j4(this)||this.player.ia("captionschanged",N2(this.g))),a||(this.g&&!j4(this)?this.player.ia("captionschanged",N2(this.g)):this.player.ia("onCaptionsTrackListChanged"));else{var b;
this.da?b=new X2(this.O.ha,this.player):this.va?b=new S2(this.l,this.O,this.player.getAudioTrack()):b=new $2(this.O.ej,this.O.videoId,this.O.Xf||this.l.Xf||g.CB(this.O,"yt:cc_default_lang")||this.l.dc,this.O.gp,this.l);this.i=b;g.F(this,this.i);b.Sq((0,g.x)(this.tL,this))}};
g.h.unload=function(){this.A&&this.g?k4(this,!1):(this.Y&&g.An(this.Y),g.FK(this.player,"captions"),this.F=[],this.i&&this.i.Hg(),this.X.clear(),this.D&&g.CK(this.player,this.D),this.Vs());g.IO.prototype.unload.call(this);var a=g.U(this.player.app);a&&g.fI(a.u);this.player.ia("captionschanged",{})};
g.h.tL=function(){var a;this.I||f4(this)?a=i4(this,this.I):g4(this)&&(a=h4(this));if(this.A||this.H){for(var b=P2(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Ez(e),srclang:O2(e),id:e.toString()};this.H||(f.src=this.i.zj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Qd("TRACK",f))}a=this.M.app.u;a.Yi(c);c=a.ga();this.la&&this.ba.K(c.textTracks,"change",this.vL)}else!this.g&&a&&m4(this,a),this.player.ia("onCaptionsTrackListChanged"),this.player.ia("onApiChange")};
g.h.vL=function(){for(var a=this.M.app.u.ga().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=P2(this.i.i,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.g:null)!=b&&m4(this,b,!0)};
g.h.XM=function(){!this.g&&this.A||this.unload()};
g.h.uL=function(a,b,c,d){if(a){this.i.Cz()&&(this.F=[],g.FK(this.M,"captions"),this.W.Aj(),this.X.reset());var e=this.X;c=c||0;d=d||0;if("string"!==typeof a){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.tu(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!V3(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<
m&&365>m){n=a[k++];var q=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if("string"!==typeof a){var w=a,z=c,C=d;if(!V3(w))throw Error("Invalid binary caption track data");e.g||(e.g=new T3(C,b));var E=e.g.o(w,z)}else{if("WEBVTT"==a.substring(0,6)){b=a;z=c;e.g||(e.g=new Y3);var G=e.g.o(b,z);.01>Math.random()&&
g.Wo(Error("Deprecated subtitles format in web player: WebVTT"));w=G}else b:{G=a;z=g.MY(G);if(!z||!z.firstChild){var H=Error("Invalid caption track data");H.params=G;throw H;}if("timedtext"==z.firstChild.tagName){if(3==parseInt(z.firstChild.getAttribute("format"),10)){if(!e.g){G={};if(C=O2(b))G.lang=C,kqa.test(C)&&(G.Ae=1);e.g=new G3(G,e.i)}w=e.g.o(z,c);break b}var P=Error("Unsupported subtitles format in web player (Format2)");P.params=G;throw P;}if("transcript"==z.firstChild.tagName){var Q=Error("Unsupported subtitles format in web player (Format1)");
Q.params=G;throw Q;}var ia=Error("Invalid caption track data");ia.params=G;throw ia;}E=w}var oa=E}catch(Va){g.L(Va),e.clear(),oa=[]}else oa=[];g.CK(this.player,oa);!this.I||this.H||j4(this)||g.Wy(this.l)||g.Xy(this.l)||(g.An(this.Y),oa=e3({Tf:0,Qe:5,Gg:5,Bk:2,textAlign:0,Ae:0,lang:"en"}),this.P=[oa],e=["Click "," for settings"],this.ea||(E=new g.OC(g.xL()),g.F(this,E),this.ea=E.element),E=oa.end-oa.start,(b=g.Ez(this.g))&&this.P.push(new b3(oa.start,E,0,oa.id,b)),this.P.push(new b3(oa.start,E,0,oa.id,
e[0]),new b3(oa.start,E,0,oa.id,this.ea,!0),new b3(oa.start,E,0,oa.id,e[1],!0)),g.CK(this.player,this.P),g.yn(this.Y));!this.I||this.H||j4(this)||(l4(this,"module-enabled",!0),this.C&&(this.C.g=this.g),(oa=g.U(this.player.app))&&g.fI(oa.u));this.I=!1}};
g.h.cF=function(a){this.F.push(a);this.W.Aj()};
g.h.dF=function(a){g.fb(this.F,a);this.i instanceof X2&&this.i.A&&g.EK(this.player,[a]);this.W.Aj()};
g.h.hM=function(a){if(a instanceof c3){var b=this.R[a.id];b&&b.o!=a&&(b.dispose(),delete this.R[a.id],b=null);b||(b=jqa(this,a))&&(this.R[a.id]=b)}else b=a.windowId,this.S[b]||(this.S[b]=[]),this.S[b].push(a)};
g.h.nM=function(){o4(this,this.P);this.P=null};
g.h.RA=function(){this.W.stop();g.$b(this.S);this.F.sort(g.TD);var a=this.F;if(this.D){var b=(0,g.Xd)(a,function(c){return-1==this.D.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.hM,this);g.Mb(this.R,function(c,d){this.S[d]?(c.element.parentNode||g.JK(this.player,c.element,4),c.xh(this.S[d])):(c.dispose(),delete this.R[d])},this)};
g.h.sM=function(){c4(this,{},!0);g.N(this.l.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ia("captionssettingschanged")};
g.h.kD=function(){var a=n4.ub;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Pe?3:a.bold?1:a.Pe?2:0,textOpacity:a.textOpacity,windowColor:n4.windowColor,windowOpacity:n4.windowOpacity};var b=d4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.XA=function(a,b){var c={};g.Sa(c,d4(this,"display-settings"));g.Sa(c,a);c4(this,c,b);this.player.ia("captionssettingschanged")};
g.h.Vs=function(){!this.A&&this.loaded&&(g.Mb(this.R,function(a,b){a.dispose();delete this.R[b]},this),this.RA())};
g.h.uc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.nd(b,-2,4);this.XA({fontSizeIncrement:c});return c;case "reload":b&&!this.A&&m4(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.l.wb&&l4(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.A)break;if(!g.Oa(b))break;if(g.Zb(b)){m4(this,null,!0);break}for(var d=P2(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?Spa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||m4(this,c,!0)}else return this.loaded&&this.g&&!j4(this)?N2(this.g):{};return"";case "tracklist":return this.i?(0,g.he)(P2(this.i.i,!(!b||!b.includeAsr)),function(k){return N2(k)}):[];
case "translationLanguages":return this.i?this.i.u.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.A||void 0==b||p4(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.l.wb&&a.push("stickyLoading");return a};
g.h.Zp=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.RM=function(){this.loaded&&this.g&&!j4(this)?(l4(this,"module-enabled",!1),this.unload(),g4(this,!0)&&m4(this,h4(this),!1)):m4(this,j4(this)||!this.g?i4(this,!0):this.g,!0)};
g.h.nI=function(){var a=j4(this);g4(this,a)?m4(this,this.player.getAudioTrack().Zl,!1):this.O.captionTracks.length&&(this.loaded&&this.unload(),this.Gk()&&(a?m4(this,i4(this),!1):this.load()))};g.QO.captions=e4;})(_yt_player);
